# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim
WORKDIR /app

# Copy only requirements then install, to leverage caching
COPY pyproject.toml requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY src ./src
COPY mcp_client.py .
# Default to stubs for .env (user should mount real .env if needed)

CMD ["python", "src/price_monitor_mcp.py"]
